### ISSUE TITLE
Uncaught TypeError: treeView.serialize is not a function

### ISSUE THREAD

**Issue by 0xAAE** [brunomgalmeida/rabbitvcs-svn#4]
[Enter steps to reproduce:]

1. Open folder that is working copy (svn)
2. Right click, then select SVN -> commit
3. There is the error (exactly the same as in TortoisSVN package in Windows)

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [rabbitvcs-svn](https://github.com/brunomgalmeida/rabbitvcs-svn) package 0.5.0

### Stack Trace

Uncaught TypeError: treeView.serialize is not a function

```
At /home/aae/.atom/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:26

TypeError: treeView.serialize is not a function
    at resolveTreeSelection (/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:26:27)
    at Object.commitFromTreeView (/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:108:16)
    at /packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:79:71)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:25.9.0 SVN:commitFromTreeView (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
rabbitvcs-svn 0.5.0 
```

**Comment by miniwark** [comment]
Seem like than `tortoise-svn` have already a patch for this same issue.

The issue:
https://github.com/jasonhwest/tortoise-svn/issues/21

The patch:
https://github.com/jasonhwest/tortoise-svn/pull/22

I have manually testest the proposed patch on `/.atom/packages/rabbitvcs-svn/lib/rabbivcs-svn.coffee` and i confirm than it fix the bug for me.

**Comment by franmartosr** [comment]
Like @miniwark said, it's the same issue as `tortoise-svn` package has before; I made the exact changes in my local version and now it works like a charm.

**Comment by brunomgalmeida** [comment]
patch merged, many thanks for helping fix this
