### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by adwiteeymauriya** [brunomgalmeida/rabbitvcs-svn#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [rabbitvcs-svn](https://github.com/brunomgalmeida/rabbitvcs-svn) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /home/adwiteey/.atom/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:31

TypeError: Cannot read property 'file' of undefined
    at resolveEditorFile (/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:31:24)
    at Object.commitFromEditor (/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:112:16)
    at /packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:80:69)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:12.1.0 SVN:commitFromEditor (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ctags 5.1.0 
atom-fuzzy-grep 0.16.0 
atom-pastebin 0.2.0 
autocomplete-python 1.10.1 
build 0.68.0 
busy 0.7.0 
docblockr 0.11.0 
Hydrogen 1.19.0 
hydrogen-launcher 1.2.1 
language-fortran 2.1.0 
paner 1.0.0 
php-integrator-autocomplete-plus 1.6.0 
platformio-ide-terminal 2.5.5 
rabbitvcs-svn 0.5.0 
script 3.15.0 
svn 0.0.13 
vim-mode-plus 0.96.2 
```

**Comment by Marc-Cox-08** [comment]
SAME issue with rabbitvcs-svn 0.6.0 Atom plugin , using Ubuntu 16.04 per : rabbitvcs-svn.coffee:30 At /home/johnsmith/.atom/packages/rabbitvcs-svn/lib/rabbitvcs-svn.coffee:30
